CREATE DATABASE Database01
GO

USE Database01
GO

CREATE TABLE Stocks (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Symbol NVARCHAR(max) NOT NULL,
	CompanyName NVARCHAR(max) NOT NULL,
	Purchase DECIMAL(18,2) NOT NULL,
	LastDiv DECIMAL(18,2) NOT NULL,
	Industry NVARCHAR(max) NOT NULL,
	MarketCap BIGINT NOT NULL
);

CREATE TABLE Comments (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Title NVARCHAR(max) NOT NULL,
	Content NVARCHAR(max) NOT NULL,
	CreatedOn DATETIME2 NOT NULL,
	StockId INT NULL, 
	FOREIGN KEY (StockId) REFERENCES Stocks(id)
);
